dist: trusty
sudo: required
language: generic

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="unicoq"
  matrix:
  - COQ_IMAGE="coqorg/coq:8.12.2"

install: |
  # Prepare the COQ container
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} ${COQ_IMAGE}
#  docker exec COQ /bin/bash --login -c "
    # This bash script is double-quoted to interpolate Travis CI env vars:
#    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
#    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
#    set -ex  # -e = exit on failure; -x = trace for debug
#    opam repo add coq-released https://coq.inria.fr/opam/released
#    opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
#    opam repo list
#    sudo apt install -y m4
#    opam pin add coq https://github.com/coq/coq.git#v8.12
#    opam config list
#    opam repo list
#    opam list
#    "
script:
- echo -e "${ANSI_YELLOW}Building ${CONTRIB_NAME}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex
    sudo chown -R opam:opam /home/coq/${CONTRIB_NAME}
    coq_makefile -f _CoqProject -o Makefile
    make
    "
- docker stop COQ  # optional
- echo -en 'travis_fold:end:script\\r'
